### ISSUE TITLE
Working version

### ISSUE THREAD

**Issue by pozirk** [SempaiGames/extension-facebookads#1]
Hey Federico!
I've tried your extension on Android, and looks like it's still not ready.
Any ideas when you are going to release some working version?
iOS version is also interested to me. :)
Thanks!

**Comment by fbricker** [comment]
Hi, I'm using this extension for android for more than 6 months now and the iOS version is working since december 2015.

Why do you say it's not still ready?

**Comment by pozirk** [comment]
Oh really.
I've tried haxelib version and couldn't get any interstitial to show up.
In my case, it stopped here:
`if(!__showInterstitial()) return false;`

I did init() first.

**Comment by fbricker** [comment]
Please provide some logs and information about your case. You should be able to see the reason using logcat.

Some points you should check are:
1) Is your game already enabled on facebook audience network?
2) Did you set up audience network to display low RPM ads? (this affects the inventory)
3) Are you sure that the lack of ads is not caused due to lack of inventory?
4) Do you see any alert on your FB App console? (sometimes Facebook alerts you on the Dev console)
5) Did you wait some hours after the first ad request to allow facebook to get inventory for you app?
6) Have you tried enabling the test ad mode?

**Comment by pozirk** [comment]
Thanks for help, I'll check it out.

**Comment by fbricker** [comment]
Ok, I'll be closing this issue now. If you find something we need to fix, please let me know and I'll re-open it.

**Comment by pozirk** [comment]
I think readme.md is kind of not ready. :)
1. It actually says "Under development..."
2. It's missing some important information, like extension-facebookads requires extension-googleplayservices-lib (and maybe extension-android-support-v4) to work properly.
Right?

**Comment by fbricker** [comment]
Ok, I've removed the "under development" text from readme.md. Thanks for that.

About dependencies:
**extension-android-support-v4:** The requirement for extension-android-support-v4 is declared on the XML and the JSON file of the extension, so this should be installed by haxelib when you do haxelib install extension-facebookads.

**extension-googleplayservices-lib:** According to facebook, this is not mandatory. At least on their website you can read:
_"Though not required, we recommend that you set up your project to work with Google Play Services as indicated here. This will enable the Audience Network SDK to fetch the Advertising ID more efficiently."_.
To be honest, I didn't tried the extension on a project where I'm not using google-playservices-lib, so I just believed Facebook on this. Did you find out something different?

Anyway: I'll like to know if the checklist I gave you was useful, since I'll be adding this checklist to the README file in case someone else has the same issues that you had.

**Comment by pozirk** [comment]
In my case FacebookAds doesn't work without `<haxelib name="extension-googleplayservices-lib" />` in my project xml file.
That's why I had problems displaying ads before.

Checklist is great, you can definitely add it to the readme.

Thank you!

**Comment by fbricker** [comment]
Oh, I see... I'll test this and add extension-googleplayservices-lib as dependency on next release.

Thanks!

**Comment by pozirk** [comment]
One more thing that would be nice to have is events to know if ad was actually served, or if there was an error, like "no internet connection" or "no fill". Was ad clicked, etc.
Thank you!
